logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081
  servlet:
    context-path: /authentication
    session:
      cookie:
        path: /authentication

security:
  oauth2:
    client:
      scope : read
      valid-access-token : 900
      authorized-grant-type : client_credentials
    resource:
      filter-order: 3
      oauth-url: http://localhost:8081/authentication/oauth/token

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth-db
    username: postgres
    password: rezaboys