logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081
  servlet:
    context-path: /authentication
    session:
      cookie:
        path: /authentication

security:
  oauth2:
    client:
      client-id: septian-reza
      client-secret : this is my secret
      scope : read
      valid-access-token : 900
      authorized-grant-type : client_credentials
    resource:
      filter-order: 3